title = "NOMAD settings"

#List all the apps you would like to be installed/updated
#Not yet used
apps = ["filezilla","npp"]

#github api key (to avoid limitations)
#Extracted from GITHUB_PAT ENV if existing
githubApiKey = "${GITHUB_PAT|paste_your_pat_here_if_not_set_by_env}"