global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using NomadGuiProgramme.DataContracts;
global using NomadGuiProgramme.DataContracts.Serialization;
global using NomadGuiProgramme.Models;
global using NomadGuiProgramme.Presentation;
global using NomadGuiProgramme.Services.Caching;
global using NomadGuiProgramme.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
