Version="5.37"
DownloadUrl="manual:http://www.joejoesoft.com/cms/file.php?f=userupload/8/files/acv{{V_MAJOR}}{{V_MINOR}}.zip"
VersionCheck={Url="https://www.joejoesoft.com/vcms/97/",RegEx="Changes in v{{VERSION}}"}
Shortcut="arsclip.exe"
RestoreFiles=["arsclip.ini","disabled.ini",""]
RestoreFolders=["clipdatabase"]
