[apps.ccleaner]
Version = "606"
Shortcut="ccleaner.exe"
DownloadUrl="https://download.ccleaner.com/portable/ccsetup{{VERSION}}.zip"
VersionCheck={Url="https://www.ccleaner.com/fr-fr/ccleaner/builds",RegEx="data-download-url=\"https://download.ccleaner.com/portable/ccsetup{{VERSION}}.zip\""}
CreateFiles={"VERSION-{{VERSION}}.txt"="{{VERSION}}"}
RestoreFiles=["backups/"]