Version="23.0.4"
RepositoryUrl="github:dbeaver/dbeaver"
DownloadUrl="{{VERSION}}/dbeaver-ce-{{VERSION}}-win32.win32.x86_64.zip"
Shortcut="dbeaver.bat"
ShortcutIcon="dbeaver.exe,0"
CreateFiles={"dbeaver.bat"="@ECHO OFF\r\nstart dbeaver.exe -data workspace6"}
RestoreFiles=["workspace6","drivers"]
CreateFolders=["workspace6/.metadata/.plugins/org.eclipse.core.resources/.projects/General"]

