Version="1.2.10.6"
RepositoryUrl="github:greenshot/greenshot"
DownloadUrl="Greenshot-RELEASE-{{VERSION}}/Greenshot-NO-INSTALLER-{{VERSION}}-RELEASE.zip"
#Shortcut="Greenshot.exe"
RestoreFiles=["Greenshot.ini"]