Version="1.3.2"
DownloadUrl="manual, download from https://inkscape.org/release/inkscape-1.3.2/windows/64-bit/compressed-7z/dl/ and convert to zip..."
DownloadExtension=".zip"
Shortcut="Run Inkscape !.bat"
#RestoreFiles=["MobaXterm.ini","MobaXterm backup.zip","session-logs"]