Version="5.5"
DownloadUrl="https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-{{VERSION}}.zip"
VersionCheck={Url="https://jmeter.apache.org/changes.html",RegEx="<h1>Version {{VERSION}}</h1>"}
Shortcut="bin/jmeter.bat"