Version="10.12.0"
VersionCheck={Url="https://dl.pstmn.io/changelog?channel=stable&platform=win64",RegEx="{\"name\":\"{{VERSION}}\""}
DownloadUrl="manual:https://dl.pstmn.io/download/{{VERSION}}/Postman-win64-{{VERSION}}-Setup.exe#/dl.7z"
Shortcut="lib/net45/Postman.exe"