Version="3.12.4.1"
VersionCheck={Url="https://winpython.github.io/",RegEx="WinPythondot-64bit-{{VERSION}}"}
DownloadUrl="https://sourceforge.net/projects/winpython/files/WinPython_{{V_MAJOR}}.{{V_MINOR}}/{{VERSION}}/Winpython64-{{VERSION}}dot.exe/download"
DownloadExtension=".7sfx"
#stores venv in this custom folder...
#RestoreFiles=["venv/"]
