# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    env:
      MAIN_PATH: "./cmd/nomad"

    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          extra-files: |
            cmd/nomad/nomad.go

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Setup token and generate
        env:
          TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: |
            echo -n "$TOKEN" > "$MAIN_PATH"/ghkey.txt
          go generate "$MAIN_PATH"

      - name: Test (discard result upon release)
        continue-on-error: ${{ steps.release.outputs.release_created }}
        run: go test ./...

      - name: Build
        run: GOOS=windows GOARCH=amd64 go build -o build-win64/ "$MAIN_PATH"

      - name: Package
        if: ${{ steps.release.outputs.release_created }}
        run: cd build-win64 && zip ../win64.zip *

      - name: Upload release binary with version info
        uses: Bertrand256/upload-release-asset@v1.0.4
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ steps.release.outputs.tag_name }}
          asset_path: win64.zip
          asset_name: nomad-${{ steps.release.outputs.major }}.${{steps.release.outputs.minor}}.${{steps.release.outputs.patch}}-win64.zip

      - name: Upload release binary without version info
        uses: Bertrand256/upload-release-asset@v1.0.4
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ steps.release.outputs.tag_name }}
          asset_path: win64.zip
          asset_name: nomad-latest-win64.zip
